#! /bin/sh

### BEGIN INIT INFO
# Provides: Runs Startup Project
# Required-Start: $all
# Required-Stop: $all
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: starts startup project Server
# Description: starts startup using start-stop-daemon
### END INIT INFO

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions


APPPATH="/var/www/startup"

#PATH=/sbin:/usr/sbin:/bin:/usr/bin:/var/www/startup
export NODE_PATH="$APPPATH:$APPPATH/node_modules"


DESC="Startup Node.js server"
NODEJS="/usr/bin/nodejs"
INDEX="/var/www/startup/index.js"
NAME=startup-node
PIDFILE="/var/run/$NAME.pid"
LOGFILE="/var/log/$NAME.log"


log()
{
    log_daemon_msg $@ | tee -a $LOGFILE
}

do_start ()
{

    if ! start-stop-daemon \
        --start \
        --background \
        --pidfile $PIDFILE \
        --exec $NODEJS \
        --test \
        > /dev/null
    then
        log_daemon_msg "$DESC is already running"
        log_end_msg 1
        exit 1
    fi

    if start-stop-daemon \
        --start \
        --background \
        --make-pidfile --pidfile $PIDFILE \
        --exec $NODEJS $INDEX \
        -- --logfile=$LOGFILE
    then
        log_daemon_msg "Starting $DESC" $NAME
        log_end_msg 0
        exit 0
    else
        log_warning_msg "Failed to start server"
        log_end_msg 1
        exit 1
    fi
}

do_stop ()
{

    if start-stop-daemon \
        --stop \
        --quiet \
        --pidfile $PIDFILE \
        --retry=TERM/30/KILL/5 \
        --exec $NODEJS
    then
        rm -f $PIDFILE

        log_daemon_msg "Stopped $DESC" $NAME
        log_end_msg 0

        if [ $@ != false ]; then
            exit 0
        fi

    else
        log_daemon_msg "Failed to stop $DESC"
        log_end_msg 1
        exit 1
    fi

}

case "$1" in
    start)
        do_start
        ;;
    stop)
        do_stop
        ;;
    restart|force-reload)
        do_stop false
        sleep 1
        do_start
    ;;
    status)
            status_of_proc "$NODEJS" "$NAME" && exit 0 || exit $?
        ;;
    *)
        N=/etc/init.d/$NAME
        echo "Usage: service $NAME {start|stop|restart|force-reload|status}" >&2
        exit 3
    ;;
esac

exit 0
