#! /bin/bash

### BEGIN INIT INFO
# Short-Description: starts startup project Server
# Description: starts startup using start-stop-daemon
### END INIT INFO

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

# vars
DATESTAMP=$(date +"%Y-%m-%d %H:%M:%S")

DESC="Startup Node.js server"
NODEJS="/usr/bin/nodejs"
NAME=startup-node
PIDFILE="/var/run/$NAME.pid"
LOGFILE="/var/log/$NAME.log"

CONFIGDIR="/etc/default"
CONFIG="$NAME"

cdir ()
{
    cd $APPPATH
}

log ()
{
    printf "\n[$NAME $DATESTAMP] $1" >> $LOGFILE
}

error ()
{
    log "ERROR: $1"
}

    # reads and sets up config
    if ! test -r $CONFIGDIR/$CONFIG
    then
        error "$CONFIGDIR/$CONFIG is not readable!"
        log_daemon_msg "$CONFIGDIR/$CONFIG is not readable!"
        log_end_msg 1
        exit 1
    fi

    #reads config file
    source $CONFIGDIR/$CONFIG

    log "Node Path: $NODE_PATH"

INDEX="${APPPATH}index.js"

# starts node daemon
do_start ()
{
    log "Changing Directory: $APPPATH"
    cdir
    
    if ! start-stop-daemon \
        --start \
        --background \
        --pidfile $PIDFILE \
        --exec $NODEJS \
        --test \
        > /dev/null
    then
        log "$DESC is alreaddy running"
        log_daemon_msg "$DESC is already running"
        log_end_msg 1
            exit 1
    fi

    if start-stop-daemon \
        --start \
        --background \
        --chuid $USER:$GROUP \
        --make-pidfile --pidfile $PIDFILE \
        --exec /bin/bash -- \
            -c "cd $APPPATH; exec $NODEJS $INDEX >> $LOGFILE 2>&1"

    then
        log_daemon_msg "Starting $DESC" $NAME
        log "Starting $DESC $NAME\n\n"
        log_end_msg 0
        exit 0
    else
        log "Failed to statt server"
        log_warning_msg "Failed to start server"
        log_end_msg 1
        exit 1
    fi
}

do_stop ()
{
    if start-stop-daemon \
        --stop \
        --quiet \
        --pidfile $PIDFILE \
        --retry=TERM/30/KILL/5 \
        --exec $NODEJS
    then
        rm -f $PIDFILE

        log "Stopped $DESC"
        log_daemon_msg "Stopped $DESC" $NAME
        log_end_msg 0

        if [ -n "$1" ] && [ $1 != false ]; then
            exit 0
        fi

    else
        log "Failed to stop $DESC"
        log_daemon_msg "Failed to stop $DESC"
        log_end_msg 1
        exit 1
    fi

}

case "$1" in
    start)
        do_start
        ;;
    stop)
        do_stop
        ;;
    restart|force-reload)
        do_stop false
        sleep 1
        do_start
    ;;
    status)
            status_of_proc "$NODEJS" "$NAME" && exit 0 || exit $?
        ;;
    *)
        N=/etc/init.d/$NAME
        echo "Usage: service $NAME {start|stop|restart|force-reload|status}" >&2
        exit 3
    ;;
esac

exit 0
